name: MiWuLa KiTa Monitor

on:
  workflow_dispatch:

jobs:
  check-kita:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt

      - name: MiWuLa Seite prüfen
        run: python monitor.py
